# Generated by Django 3.2.9 on 2021-12-10 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.brand'),
        ),
    ]
