# Generated by Django 4.0 on 2021-12-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_product_brand_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='camera',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='display',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='os',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='processor',
            field=models.CharField(max_length=50),
        ),
    ]
