# Generated by Django 4.0 on 2021-12-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_product_camera_alter_product_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='camera',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='display',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='os',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='processor',
            field=models.CharField(max_length=100),
        ),
    ]
