# Generated by Django 4.0 on 2022-03-05 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_product_camera_alter_product_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.address'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('COD', 'COD'), ('UPI', 'UPI'), ('Net Banking', 'Net Banking'), ('Credit/Debit Card', 'Credit/Debit Card')], max_length=100),
        ),
    ]
