# Generated by Django 4.0 on 2022-03-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_rename_order_review_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
    ]
