# Generated by Django 4.0 on 2022-03-29 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_rename_product_cart_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='user_id',
        ),
    ]
